### PR TITLE
Start of Translations

### PR DESCRIPTION
**Pull request by Yusarina**
- This is the start of the translations system, does not yet work as I can't seem to get it to swap languages, I too tired today to fix it but it's a start.
- It also adds properties registration as well.

Do not merge yet, this is not ready!

https://github.com/unofficalcats/Avatar-Toolkit/issues/10

### CODE REVIEW

**Comment by Yusarina** [comment]
Translation System now works, I just have to get all the current functions into the json file and then this should be ready to merge.

**Comment by Yusarina** [comment]
Category Lables (Submenu Lables) and Descriptions don't seem to be translating, unsure why, the only thing I can think of is because it doesn't work with the Refresh method I am trying to use. However the old way of doing it (Reloading the plugin) isn't the best way as well, but we may need to resort to this. 

The main UI such as buttons and labels do seem to be working fine though.

**Comment by Yusarina** [comment]
Ok This has been updated with the following:

- Added addon_preferences so we can save users preferences into a json file.
- Made translation slightly simpler

This mostly works just have to figure out why we can't update description on reload (There only update on blender restart). For the life of me I tried over 10 different ways where this should update including reloading the classes (Unregister them and register them again) and it still doesn't work. It's possible something has changed in Blender 4.3 but I have no idea I am stumped and could just be being blind and missing something.

**Comment by Yusarina** [comment]
@989onan Ready for review and mergeing.

**Comment by 989onan** [comment]
Okay I reviewed it, but I have one small gripe

The Json for the languages should have "messages" (WHICH IT DOES) but also it should have "authors" which should be an array of the people who did the translation
This way the translation can have the authors in the description or something when switching to it. Credits and all of that ^_^

After that change, it can be merged no problem, it gets my automatic approval

**Comment by Yusarina** [comment]
This is now done and authors has been added to the json file, I gonna merge as you said it get's you automatic approveal and because this PR is breaking other stuff now.

**Pull request merged**
