### PR TITLE
Remove Bone constraints

### PR DESCRIPTION
**Pull request by Yusarina**
- Adds Remove Bone Constraints, this uses pose mode instead of edit mode as this is supposedly a safer method.

### CODE REVIEW

**Review by 989onan — APPROVED** [review]
Never thought to use a while statement, but this looks good
This will be perfect for those rigs from blender people want to put into
VRC or Resonite but can't due to how many constraints there are.

IMPORTANT:
This will need some testing to make sure that the armature doesn't implode when constraints are removed this way. Other plugins like Cats were able to remove the constraints but prevent armature implosion even if the constraints were complex
Hopefully this can do the same.

**Comment by Yusarina** [comment]
In my initial testing it seemed to work just fine, however I will test some more later to make sure.

As this operations in pose mode it's designed to safely remove bone constraints without causing the armature to implode or break. as it operates on the pose bones, which doesn't affect the underlying armature structure. Unlike if you use Edit mode which can effect the underlying armature structure. Or that's atleast according to the blender devs atleast, it is blender so anything can happen xD.

**Comment by 989onan** [comment]
Well I mean't some constrains can rely on others to keep bones in position in pose mode, and removing them can cause implosion

Though the armatures that do that are few and far inbetween. anyways once conflicts are resolved this can be merged ^_^

**Comment by Yusarina** [comment]
Well I thought I left a comment on here.

60 different models tested, no issues found, mmd, vrm and fbx. If the above happens we will deal with it, however from what I understand this may of been a pre 3.0 issue but it should no longer do this. We keep our eye on it if it pops up I can always change how we do it.

**Pull request merged**
