### PR TITLE
Basic Start of Armature Selection

### PR DESCRIPTION
**Pull request by Yusarina**
This is the very basic start of the Armature Sections system for Avatar Toolkit. 

The system itself works and some of the current functions work just fine, however a couple of them may need adapting which I will do. 

To-do
- Helper function to return all mehses to help with exclusion later.
- Make sure all current functions, function as intended.

### CODE REVIEW

**Comment by Yusarina** [comment]
Latest commit does the following:

- Added a check to make sure Armature is valid.
- Added a helper to select the current armature  selected in armature selection.
- Added a helper to get all meshes.
- Updated all current functions to work with the system.

This makes the To-Do list complete and this is I beleive ready for prime time unless I missing something, I know we want a mesh selection system but I beleive this might be a future thing maybe? @989onan do you agree this is ready? or should we expand?

**Comment by 989onan** [comment]
mesh selection should be a future thing, I'll look tomorrow I'm exhausted right now

**Comment by 989onan** [comment]
This looks amazing! I like how it has many helper methods and blocks the user from using the UI tools unless they selected an armature. Merging ^_^

**Comment by Yusarina** [comment]
Yea I thought this would be the best way of doing things! thanks!

**Pull request merged**
